%% draw fixation
function drawFixation(task)
    global stimulus
    
    mglTextSet('Helvetica',24,[1 1 1],0,0,0,1,0,0,0);
    thisText = mglText('please fixate');
    
    if isfield(stimulus,'FixationBreakCurrent')
        checkFix=stimulus.FixationBreakCurrent;
    else
        checkFix=0;
    end
        
    if  checkFix && (1 <= task.thistrial.thisseg < 9)  %(stimulus.FixationBreak(task.trialnum))  %If there is a fixn break, present 
       mglBltTexture(thisText,[0 0],'left','top');
    
    elseif  (task.thistrial.thisseg >= 9)
        
        mglLines2([stimulus.FCloc{1}(1,1),stimulus.FCloc{2}(1,1)],...
                  [stimulus.FCloc{1}(1,2),stimulus.FCloc{2}(1,2)],...
                  [stimulus.FCloc{1}(2,1),stimulus.FCloc{2}(2,1)],...
                  [stimulus.FCloc{1}(2,2),stimulus.FCloc{2}(2,2)],...
                   stimulus.FClinewidth,stimulus.black,1);
%         mglFixationCross(stimulus.FCwidth,stimulus.FClinewidth,stimulus.black); %if there is no response & it is not the response window or feedback window, just present white fixation
    
    elseif ~task.thistrial.gotResponse || (task.thistrial.thisseg == 9)
        mglLines2([stimulus.FCloc{1}(1,1),stimulus.FCloc{2}(1,1)],...
                  [stimulus.FCloc{1}(1,2),stimulus.FCloc{2}(1,2)],...
                  [stimulus.FCloc{1}(2,1),stimulus.FCloc{2}(2,1)],...
                  [stimulus.FCloc{1}(2,2),stimulus.FCloc{2}(2,2)],...
                   stimulus.FClinewidth,stimulus.white,1);
%         mglFixationCross(stimulus.FCwidth,stimulus.FClinewidth,stimulus.white); %if there is no response & it is not the response window or feedback window, just present white fixation
    
    elseif (task.thistrial.thisseg == 7 && ~task.thistrial.gotResponse); %No fixation before response
        mglLines2([stimulus.FCloc{1}(1,1),stimulus.FCloc{2}(1,1)],...
                  [stimulus.FCloc{1}(1,2),stimulus.FCloc{2}(1,2)],...
                  [stimulus.FCloc{1}(2,1),stimulus.FCloc{2}(2,1)],...
                  [stimulus.FCloc{1}(2,2),stimulus.FCloc{2}(2,2)],...
                   stimulus.FClinewidth,stimulus.white,1);
    elseif ((task.thistrial.thisseg == 7 && task.thistrial.gotResponse) || (task.thistrial.thisseg == 8 && task.thistrial.gotResponse)) %Once there is a response, present fixation of a different color
        if stimulus.tmp.response == 1
            mglLines2([stimulus.FCloc{1}(1,1),stimulus.FCloc{2}(1,1)],...
                      [stimulus.FCloc{1}(1,2),stimulus.FCloc{2}(1,2)],...
                      [stimulus.FCloc{1}(2,1),stimulus.FCloc{2}(2,1)],...
                      [stimulus.FCloc{1}(2,2),stimulus.FCloc{2}(2,2)],...
                       stimulus.FClinewidth,stimulus.greencorrect,1);
%             mglFixationCross(stimulus.FCwidth,stimulus.FClinewidth,stimulus.greencorrect);
        elseif stimulus.tmp.response == 0
            mglLines2([stimulus.FCloc{1}(1,1),stimulus.FCloc{2}(1,1)],...
                      [stimulus.FCloc{1}(1,2),stimulus.FCloc{2}(1,2)],...
                      [stimulus.FCloc{1}(2,1),stimulus.FCloc{2}(2,1)],...
                      [stimulus.FCloc{1}(2,2),stimulus.FCloc{2}(2,2)],...
                       stimulus.FClinewidth,stimulus.redincorrect,1);
%             mglFixationCross(stimulus.FCwidth,stimulus.FClinewidth,stimulus.redincorrect); 
        end
    
    elseif (task.thistrial.thisseg == 8 && ~task.thistrial.gotResponse)  %If there is no response, present orange fixation
        mglLines2([stimulus.FCloc{1}(1,1),stimulus.FCloc{2}(1,1)],...
                  [stimulus.FCloc{1}(1,2),stimulus.FCloc{2}(1,2)],...
                  [stimulus.FCloc{1}(2,1),stimulus.FCloc{2}(2,1)],...
                  [stimulus.FCloc{1}(2,2),stimulus.FCloc{2}(2,2)],...
                   stimulus.FClinewidth,stimulus.orangenoanswer,1);
%         mglFixationCross(stimulus.FCwidth,stimulus.FClinewidth,stimulus.orangenoanswer);
    
    end
end